// Auto-generated. Do not edit!

// (in-package actionlib_tutorials.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class FibonacciGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.destination = null;
      this.order = null;
    }
    else {
      if (initObj.hasOwnProperty('destination')) {
        this.destination = initObj.destination
      }
      else {
        this.destination = new geometry_msgs.msg.Point();
      }
      if (initObj.hasOwnProperty('order')) {
        this.order = initObj.order
      }
      else {
        this.order = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type FibonacciGoal
    // Serialize message field [destination]
    bufferOffset = geometry_msgs.msg.Point.serialize(obj.destination, buffer, bufferOffset);
    // Serialize message field [order]
    bufferOffset = _serializer.uint32(obj.order, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type FibonacciGoal
    let len;
    let data = new FibonacciGoal(null);
    // Deserialize message field [destination]
    data.destination = geometry_msgs.msg.Point.deserialize(buffer, bufferOffset);
    // Deserialize message field [order]
    data.order = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 28;
  }

  static datatype() {
    // Returns string type for a message object
    return 'actionlib_tutorials/FibonacciGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '945a608169e58de4791dd58bf822705a';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    
    #Where to go
    geometry_msgs/Point destination
    
    #Who to call
    uint32 order
    
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new FibonacciGoal(null);
    if (msg.destination !== undefined) {
      resolved.destination = geometry_msgs.msg.Point.Resolve(msg.destination)
    }
    else {
      resolved.destination = new geometry_msgs.msg.Point()
    }

    if (msg.order !== undefined) {
      resolved.order = msg.order;
    }
    else {
      resolved.order = 0
    }

    return resolved;
    }
};

module.exports = FibonacciGoal;
