// Auto-generated. Do not edit!

// (in-package actionlib_tutorials.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class LidarGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.margin = null;
    }
    else {
      if (initObj.hasOwnProperty('margin')) {
        this.margin = initObj.margin
      }
      else {
        this.margin = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type LidarGoal
    // Serialize message field [margin]
    bufferOffset = _serializer.int32(obj.margin, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type LidarGoal
    let len;
    let data = new LidarGoal(null);
    // Deserialize message field [margin]
    data.margin = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'actionlib_tutorials/LidarGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '56ede3025f9af8ca5f4030e86d8db223';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    int32 margin
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new LidarGoal(null);
    if (msg.margin !== undefined) {
      resolved.margin = msg.margin;
    }
    else {
      resolved.margin = 0
    }

    return resolved;
    }
};

module.exports = LidarGoal;
