// Generated by gencpp from file actionlib_tutorials/doTrajGoal.msg
// DO NOT EDIT!


#ifndef ACTIONLIB_TUTORIALS_MESSAGE_DOTRAJGOAL_H
#define ACTIONLIB_TUTORIALS_MESSAGE_DOTRAJGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace actionlib_tutorials
{
template <class ContainerAllocator>
struct doTrajGoal_
{
  typedef doTrajGoal_<ContainerAllocator> Type;

  doTrajGoal_()
    : shape(0)
    , id(0)  {
    }
  doTrajGoal_(const ContainerAllocator& _alloc)
    : shape(0)
    , id(0)  {
  (void)_alloc;
    }



   typedef uint32_t _shape_type;
  _shape_type shape;

   typedef uint32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::actionlib_tutorials::doTrajGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actionlib_tutorials::doTrajGoal_<ContainerAllocator> const> ConstPtr;

}; // struct doTrajGoal_

typedef ::actionlib_tutorials::doTrajGoal_<std::allocator<void> > doTrajGoal;

typedef boost::shared_ptr< ::actionlib_tutorials::doTrajGoal > doTrajGoalPtr;
typedef boost::shared_ptr< ::actionlib_tutorials::doTrajGoal const> doTrajGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actionlib_tutorials::doTrajGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actionlib_tutorials::doTrajGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::actionlib_tutorials::doTrajGoal_<ContainerAllocator1> & lhs, const ::actionlib_tutorials::doTrajGoal_<ContainerAllocator2> & rhs)
{
  return lhs.shape == rhs.shape &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::actionlib_tutorials::doTrajGoal_<ContainerAllocator1> & lhs, const ::actionlib_tutorials::doTrajGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace actionlib_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_tutorials::doTrajGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_tutorials::doTrajGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_tutorials::doTrajGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_tutorials::doTrajGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_tutorials::doTrajGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_tutorials::doTrajGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actionlib_tutorials::doTrajGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b74ad18bcfc3cc0f3d1ad38770f7e67";
  }

  static const char* value(const ::actionlib_tutorials::doTrajGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b74ad18bcfc3cc0ULL;
  static const uint64_t static_value2 = 0xf3d1ad38770f7e67ULL;
};

template<class ContainerAllocator>
struct DataType< ::actionlib_tutorials::doTrajGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actionlib_tutorials/doTrajGoal";
  }

  static const char* value(const ::actionlib_tutorials::doTrajGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actionlib_tutorials::doTrajGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# This is an action definition file, which has three parts: the goal\n"
"# the result, and the feedback.\n"
"# Part 1: the goal.\n"
"#\n"
"# The angle in degree the robot to turn, sent by client main\n"
"uint32 shape\n"
"uint32 id\n"
;
  }

  static const char* value(const ::actionlib_tutorials::doTrajGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actionlib_tutorials::doTrajGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.shape);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct doTrajGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actionlib_tutorials::doTrajGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::actionlib_tutorials::doTrajGoal_<ContainerAllocator>& v)
  {
    s << indent << "shape: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.shape);
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTIONLIB_TUTORIALS_MESSAGE_DOTRAJGOAL_H
