// Generated by gencpp from file actionlib_tutorials/killMotorsRequest.msg
// DO NOT EDIT!


#ifndef ACTIONLIB_TUTORIALS_MESSAGE_KILLMOTORSREQUEST_H
#define ACTIONLIB_TUTORIALS_MESSAGE_KILLMOTORSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace actionlib_tutorials
{
template <class ContainerAllocator>
struct killMotorsRequest_
{
  typedef killMotorsRequest_<ContainerAllocator> Type;

  killMotorsRequest_()
    : id(0)  {
    }
  killMotorsRequest_(const ContainerAllocator& _alloc)
    : id(0)  {
  (void)_alloc;
    }



   typedef int64_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::actionlib_tutorials::killMotorsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actionlib_tutorials::killMotorsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct killMotorsRequest_

typedef ::actionlib_tutorials::killMotorsRequest_<std::allocator<void> > killMotorsRequest;

typedef boost::shared_ptr< ::actionlib_tutorials::killMotorsRequest > killMotorsRequestPtr;
typedef boost::shared_ptr< ::actionlib_tutorials::killMotorsRequest const> killMotorsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actionlib_tutorials::killMotorsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actionlib_tutorials::killMotorsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::actionlib_tutorials::killMotorsRequest_<ContainerAllocator1> & lhs, const ::actionlib_tutorials::killMotorsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::actionlib_tutorials::killMotorsRequest_<ContainerAllocator1> & lhs, const ::actionlib_tutorials::killMotorsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace actionlib_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_tutorials::killMotorsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_tutorials::killMotorsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_tutorials::killMotorsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_tutorials::killMotorsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_tutorials::killMotorsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_tutorials::killMotorsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actionlib_tutorials::killMotorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef7df1d34137d3879d089ad803388efa";
  }

  static const char* value(const ::actionlib_tutorials::killMotorsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef7df1d34137d387ULL;
  static const uint64_t static_value2 = 0x9d089ad803388efaULL;
};

template<class ContainerAllocator>
struct DataType< ::actionlib_tutorials::killMotorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actionlib_tutorials/killMotorsRequest";
  }

  static const char* value(const ::actionlib_tutorials::killMotorsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actionlib_tutorials::killMotorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 id\n"
;
  }

  static const char* value(const ::actionlib_tutorials::killMotorsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actionlib_tutorials::killMotorsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct killMotorsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actionlib_tutorials::killMotorsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::actionlib_tutorials::killMotorsRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTIONLIB_TUTORIALS_MESSAGE_KILLMOTORSREQUEST_H
