// Generated by gencpp from file actionlib_tutorials/killMotors.msg
// DO NOT EDIT!


#ifndef ACTIONLIB_TUTORIALS_MESSAGE_KILLMOTORS_H
#define ACTIONLIB_TUTORIALS_MESSAGE_KILLMOTORS_H

#include <ros/service_traits.h>


#include <actionlib_tutorials/killMotorsRequest.h>
#include <actionlib_tutorials/killMotorsResponse.h>


namespace actionlib_tutorials
{

struct killMotors
{

typedef killMotorsRequest Request;
typedef killMotorsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct killMotors
} // namespace actionlib_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::actionlib_tutorials::killMotors > {
  static const char* value()
  {
    return "77c661ef85dbd8d8b9b8b41a8c29118f";
  }

  static const char* value(const ::actionlib_tutorials::killMotors&) { return value(); }
};

template<>
struct DataType< ::actionlib_tutorials::killMotors > {
  static const char* value()
  {
    return "actionlib_tutorials/killMotors";
  }

  static const char* value(const ::actionlib_tutorials::killMotors&) { return value(); }
};


// service_traits::MD5Sum< ::actionlib_tutorials::killMotorsRequest> should match
// service_traits::MD5Sum< ::actionlib_tutorials::killMotors >
template<>
struct MD5Sum< ::actionlib_tutorials::killMotorsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::actionlib_tutorials::killMotors >::value();
  }
  static const char* value(const ::actionlib_tutorials::killMotorsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::actionlib_tutorials::killMotorsRequest> should match
// service_traits::DataType< ::actionlib_tutorials::killMotors >
template<>
struct DataType< ::actionlib_tutorials::killMotorsRequest>
{
  static const char* value()
  {
    return DataType< ::actionlib_tutorials::killMotors >::value();
  }
  static const char* value(const ::actionlib_tutorials::killMotorsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::actionlib_tutorials::killMotorsResponse> should match
// service_traits::MD5Sum< ::actionlib_tutorials::killMotors >
template<>
struct MD5Sum< ::actionlib_tutorials::killMotorsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::actionlib_tutorials::killMotors >::value();
  }
  static const char* value(const ::actionlib_tutorials::killMotorsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::actionlib_tutorials::killMotorsResponse> should match
// service_traits::DataType< ::actionlib_tutorials::killMotors >
template<>
struct DataType< ::actionlib_tutorials::killMotorsResponse>
{
  static const char* value()
  {
    return DataType< ::actionlib_tutorials::killMotors >::value();
  }
  static const char* value(const ::actionlib_tutorials::killMotorsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ACTIONLIB_TUTORIALS_MESSAGE_KILLMOTORS_H
