// Generated by gencpp from file actionlib_tutorials/killMotorsResponse.msg
// DO NOT EDIT!


#ifndef ACTIONLIB_TUTORIALS_MESSAGE_KILLMOTORSRESPONSE_H
#define ACTIONLIB_TUTORIALS_MESSAGE_KILLMOTORSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace actionlib_tutorials
{
template <class ContainerAllocator>
struct killMotorsResponse_
{
  typedef killMotorsResponse_<ContainerAllocator> Type;

  killMotorsResponse_()
    : result(0)  {
    }
  killMotorsResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int64_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::actionlib_tutorials::killMotorsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actionlib_tutorials::killMotorsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct killMotorsResponse_

typedef ::actionlib_tutorials::killMotorsResponse_<std::allocator<void> > killMotorsResponse;

typedef boost::shared_ptr< ::actionlib_tutorials::killMotorsResponse > killMotorsResponsePtr;
typedef boost::shared_ptr< ::actionlib_tutorials::killMotorsResponse const> killMotorsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actionlib_tutorials::killMotorsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actionlib_tutorials::killMotorsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::actionlib_tutorials::killMotorsResponse_<ContainerAllocator1> & lhs, const ::actionlib_tutorials::killMotorsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::actionlib_tutorials::killMotorsResponse_<ContainerAllocator1> & lhs, const ::actionlib_tutorials::killMotorsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace actionlib_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_tutorials::killMotorsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_tutorials::killMotorsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_tutorials::killMotorsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_tutorials::killMotorsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_tutorials::killMotorsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_tutorials::killMotorsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actionlib_tutorials::killMotorsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b05623554ab950ed237d43d45f0b4dd";
  }

  static const char* value(const ::actionlib_tutorials::killMotorsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b05623554ab950eULL;
  static const uint64_t static_value2 = 0xd237d43d45f0b4ddULL;
};

template<class ContainerAllocator>
struct DataType< ::actionlib_tutorials::killMotorsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actionlib_tutorials/killMotorsResponse";
  }

  static const char* value(const ::actionlib_tutorials::killMotorsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actionlib_tutorials::killMotorsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 result\n"
;
  }

  static const char* value(const ::actionlib_tutorials::killMotorsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actionlib_tutorials::killMotorsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct killMotorsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actionlib_tutorials::killMotorsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::actionlib_tutorials::killMotorsResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int64_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTIONLIB_TUTORIALS_MESSAGE_KILLMOTORSRESPONSE_H
