// Generated by gencpp from file actionlib_tutorials/LidarResult.msg
// DO NOT EDIT!


#ifndef ACTIONLIB_TUTORIALS_MESSAGE_LIDARRESULT_H
#define ACTIONLIB_TUTORIALS_MESSAGE_LIDARRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace actionlib_tutorials
{
template <class ContainerAllocator>
struct LidarResult_
{
  typedef LidarResult_<ContainerAllocator> Type;

  LidarResult_()
    : final(0)  {
    }
  LidarResult_(const ContainerAllocator& _alloc)
    : final(0)  {
  (void)_alloc;
    }



   typedef int32_t _final_type;
  _final_type final;





  typedef boost::shared_ptr< ::actionlib_tutorials::LidarResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actionlib_tutorials::LidarResult_<ContainerAllocator> const> ConstPtr;

}; // struct LidarResult_

typedef ::actionlib_tutorials::LidarResult_<std::allocator<void> > LidarResult;

typedef boost::shared_ptr< ::actionlib_tutorials::LidarResult > LidarResultPtr;
typedef boost::shared_ptr< ::actionlib_tutorials::LidarResult const> LidarResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actionlib_tutorials::LidarResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actionlib_tutorials::LidarResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::actionlib_tutorials::LidarResult_<ContainerAllocator1> & lhs, const ::actionlib_tutorials::LidarResult_<ContainerAllocator2> & rhs)
{
  return lhs.final == rhs.final;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::actionlib_tutorials::LidarResult_<ContainerAllocator1> & lhs, const ::actionlib_tutorials::LidarResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace actionlib_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_tutorials::LidarResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_tutorials::LidarResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_tutorials::LidarResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_tutorials::LidarResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_tutorials::LidarResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_tutorials::LidarResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actionlib_tutorials::LidarResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2aa29bfa110a0d8eeafa337cf7fa549";
  }

  static const char* value(const ::actionlib_tutorials::LidarResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2aa29bfa110a0d8ULL;
  static const uint64_t static_value2 = 0xeeafa337cf7fa549ULL;
};

template<class ContainerAllocator>
struct DataType< ::actionlib_tutorials::LidarResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actionlib_tutorials/LidarResult";
  }

  static const char* value(const ::actionlib_tutorials::LidarResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actionlib_tutorials::LidarResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"int32 final\n"
;
  }

  static const char* value(const ::actionlib_tutorials::LidarResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actionlib_tutorials::LidarResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.final);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LidarResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actionlib_tutorials::LidarResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::actionlib_tutorials::LidarResult_<ContainerAllocator>& v)
  {
    s << indent << "final: ";
    Printer<int32_t>::stream(s, indent + "  ", v.final);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTIONLIB_TUTORIALS_MESSAGE_LIDARRESULT_H
