// Generated by gencpp from file actionlib_tutorials/LidarGoal.msg
// DO NOT EDIT!


#ifndef ACTIONLIB_TUTORIALS_MESSAGE_LIDARGOAL_H
#define ACTIONLIB_TUTORIALS_MESSAGE_LIDARGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace actionlib_tutorials
{
template <class ContainerAllocator>
struct LidarGoal_
{
  typedef LidarGoal_<ContainerAllocator> Type;

  LidarGoal_()
    : margin(0)  {
    }
  LidarGoal_(const ContainerAllocator& _alloc)
    : margin(0)  {
  (void)_alloc;
    }



   typedef int32_t _margin_type;
  _margin_type margin;





  typedef boost::shared_ptr< ::actionlib_tutorials::LidarGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actionlib_tutorials::LidarGoal_<ContainerAllocator> const> ConstPtr;

}; // struct LidarGoal_

typedef ::actionlib_tutorials::LidarGoal_<std::allocator<void> > LidarGoal;

typedef boost::shared_ptr< ::actionlib_tutorials::LidarGoal > LidarGoalPtr;
typedef boost::shared_ptr< ::actionlib_tutorials::LidarGoal const> LidarGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actionlib_tutorials::LidarGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actionlib_tutorials::LidarGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::actionlib_tutorials::LidarGoal_<ContainerAllocator1> & lhs, const ::actionlib_tutorials::LidarGoal_<ContainerAllocator2> & rhs)
{
  return lhs.margin == rhs.margin;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::actionlib_tutorials::LidarGoal_<ContainerAllocator1> & lhs, const ::actionlib_tutorials::LidarGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace actionlib_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_tutorials::LidarGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_tutorials::LidarGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_tutorials::LidarGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_tutorials::LidarGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_tutorials::LidarGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_tutorials::LidarGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actionlib_tutorials::LidarGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "56ede3025f9af8ca5f4030e86d8db223";
  }

  static const char* value(const ::actionlib_tutorials::LidarGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x56ede3025f9af8caULL;
  static const uint64_t static_value2 = 0x5f4030e86d8db223ULL;
};

template<class ContainerAllocator>
struct DataType< ::actionlib_tutorials::LidarGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actionlib_tutorials/LidarGoal";
  }

  static const char* value(const ::actionlib_tutorials::LidarGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actionlib_tutorials::LidarGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"int32 margin\n"
;
  }

  static const char* value(const ::actionlib_tutorials::LidarGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actionlib_tutorials::LidarGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.margin);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LidarGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actionlib_tutorials::LidarGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::actionlib_tutorials::LidarGoal_<ContainerAllocator>& v)
  {
    s << indent << "margin: ";
    Printer<int32_t>::stream(s, indent + "  ", v.margin);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTIONLIB_TUTORIALS_MESSAGE_LIDARGOAL_H
