// Generated by gencpp from file actionlib_tutorials/my_newResult.msg
// DO NOT EDIT!


#ifndef ACTIONLIB_TUTORIALS_MESSAGE_MY_NEWRESULT_H
#define ACTIONLIB_TUTORIALS_MESSAGE_MY_NEWRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace actionlib_tutorials
{
template <class ContainerAllocator>
struct my_newResult_
{
  typedef my_newResult_<ContainerAllocator> Type;

  my_newResult_()
    : time_elapsed()
    , updates_n(0)  {
    }
  my_newResult_(const ContainerAllocator& _alloc)
    : time_elapsed()
    , updates_n(0)  {
  (void)_alloc;
    }



   typedef ros::Duration _time_elapsed_type;
  _time_elapsed_type time_elapsed;

   typedef uint32_t _updates_n_type;
  _updates_n_type updates_n;





  typedef boost::shared_ptr< ::actionlib_tutorials::my_newResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actionlib_tutorials::my_newResult_<ContainerAllocator> const> ConstPtr;

}; // struct my_newResult_

typedef ::actionlib_tutorials::my_newResult_<std::allocator<void> > my_newResult;

typedef boost::shared_ptr< ::actionlib_tutorials::my_newResult > my_newResultPtr;
typedef boost::shared_ptr< ::actionlib_tutorials::my_newResult const> my_newResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actionlib_tutorials::my_newResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actionlib_tutorials::my_newResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::actionlib_tutorials::my_newResult_<ContainerAllocator1> & lhs, const ::actionlib_tutorials::my_newResult_<ContainerAllocator2> & rhs)
{
  return lhs.time_elapsed == rhs.time_elapsed &&
    lhs.updates_n == rhs.updates_n;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::actionlib_tutorials::my_newResult_<ContainerAllocator1> & lhs, const ::actionlib_tutorials::my_newResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace actionlib_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_tutorials::my_newResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_tutorials::my_newResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_tutorials::my_newResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_tutorials::my_newResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_tutorials::my_newResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_tutorials::my_newResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actionlib_tutorials::my_newResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ec7b9dd60f0cbf3a48147f1dd0e2c305";
  }

  static const char* value(const ::actionlib_tutorials::my_newResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xec7b9dd60f0cbf3aULL;
  static const uint64_t static_value2 = 0x48147f1dd0e2c305ULL;
};

template<class ContainerAllocator>
struct DataType< ::actionlib_tutorials::my_newResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actionlib_tutorials/my_newResult";
  }

  static const char* value(const ::actionlib_tutorials::my_newResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actionlib_tutorials::my_newResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Part 2: the result, sent by action server unpon completion\n"
"#\n"
"# How much time used\n"
"duration time_elapsed\n"
"# How many updates thrown in total\n"
"uint32 updates_n\n"
;
  }

  static const char* value(const ::actionlib_tutorials::my_newResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actionlib_tutorials::my_newResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time_elapsed);
      stream.next(m.updates_n);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_newResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actionlib_tutorials::my_newResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::actionlib_tutorials::my_newResult_<ContainerAllocator>& v)
  {
    s << indent << "time_elapsed: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.time_elapsed);
    s << indent << "updates_n: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.updates_n);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTIONLIB_TUTORIALS_MESSAGE_MY_NEWRESULT_H
