; Auto-generated. Do not edit!


(cl:in-package actionlib_tutorials-msg)


;//! \htmlinclude doTrajGoal.msg.html

(cl:defclass <doTrajGoal> (roslisp-msg-protocol:ros-message)
  ((shape
    :reader shape
    :initarg :shape
    :type cl:integer
    :initform 0)
   (id
    :reader id
    :initarg :id
    :type cl:integer
    :initform 0))
)

(cl:defclass doTrajGoal (<doTrajGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <doTrajGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'doTrajGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name actionlib_tutorials-msg:<doTrajGoal> is deprecated: use actionlib_tutorials-msg:doTrajGoal instead.")))

(cl:ensure-generic-function 'shape-val :lambda-list '(m))
(cl:defmethod shape-val ((m <doTrajGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader actionlib_tutorials-msg:shape-val is deprecated.  Use actionlib_tutorials-msg:shape instead.")
  (shape m))

(cl:ensure-generic-function 'id-val :lambda-list '(m))
(cl:defmethod id-val ((m <doTrajGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader actionlib_tutorials-msg:id-val is deprecated.  Use actionlib_tutorials-msg:id instead.")
  (id m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <doTrajGoal>) ostream)
  "Serializes a message object of type '<doTrajGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'shape)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'shape)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'shape)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'shape)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'id)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <doTrajGoal>) istream)
  "Deserializes a message object of type '<doTrajGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'shape)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'shape)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'shape)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'shape)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'id)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<doTrajGoal>)))
  "Returns string type for a message object of type '<doTrajGoal>"
  "actionlib_tutorials/doTrajGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'doTrajGoal)))
  "Returns string type for a message object of type 'doTrajGoal"
  "actionlib_tutorials/doTrajGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<doTrajGoal>)))
  "Returns md5sum for a message object of type '<doTrajGoal>"
  "8b74ad18bcfc3cc0f3d1ad38770f7e67")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'doTrajGoal)))
  "Returns md5sum for a message object of type 'doTrajGoal"
  "8b74ad18bcfc3cc0f3d1ad38770f7e67")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<doTrajGoal>)))
  "Returns full string definition for message of type '<doTrajGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# This is an action definition file, which has three parts: the goal~%# the result, and the feedback.~%# Part 1: the goal.~%#~%# The angle in degree the robot to turn, sent by client main~%uint32 shape~%uint32 id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'doTrajGoal)))
  "Returns full string definition for message of type 'doTrajGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# This is an action definition file, which has three parts: the goal~%# the result, and the feedback.~%# Part 1: the goal.~%#~%# The angle in degree the robot to turn, sent by client main~%uint32 shape~%uint32 id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <doTrajGoal>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <doTrajGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'doTrajGoal
    (cl:cons ':shape (shape msg))
    (cl:cons ':id (id msg))
))
