; Auto-generated. Do not edit!


(cl:in-package actionlib_tutorials-msg)


;//! \htmlinclude LidarFeedback.msg.html

(cl:defclass <LidarFeedback> (roslisp-msg-protocol:ros-message)
  ((distance
    :reader distance
    :initarg :distance
    :type cl:integer
    :initform 0))
)

(cl:defclass LidarFeedback (<LidarFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LidarFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LidarFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name actionlib_tutorials-msg:<LidarFeedback> is deprecated: use actionlib_tutorials-msg:LidarFeedback instead.")))

(cl:ensure-generic-function 'distance-val :lambda-list '(m))
(cl:defmethod distance-val ((m <LidarFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader actionlib_tutorials-msg:distance-val is deprecated.  Use actionlib_tutorials-msg:distance instead.")
  (distance m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LidarFeedback>) ostream)
  "Serializes a message object of type '<LidarFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'distance)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LidarFeedback>) istream)
  "Deserializes a message object of type '<LidarFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'distance) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LidarFeedback>)))
  "Returns string type for a message object of type '<LidarFeedback>"
  "actionlib_tutorials/LidarFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LidarFeedback)))
  "Returns string type for a message object of type 'LidarFeedback"
  "actionlib_tutorials/LidarFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LidarFeedback>)))
  "Returns md5sum for a message object of type '<LidarFeedback>"
  "680f8923bb6b23ec7057fffc11ea7b34")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LidarFeedback)))
  "Returns md5sum for a message object of type 'LidarFeedback"
  "680f8923bb6b23ec7057fffc11ea7b34")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LidarFeedback>)))
  "Returns full string definition for message of type '<LidarFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 distance~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LidarFeedback)))
  "Returns full string definition for message of type 'LidarFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 distance~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LidarFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LidarFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'LidarFeedback
    (cl:cons ':distance (distance msg))
))
