; Auto-generated. Do not edit!


(cl:in-package actionlib_tutorials-msg)


;//! \htmlinclude LidarGoal.msg.html

(cl:defclass <LidarGoal> (roslisp-msg-protocol:ros-message)
  ((margin
    :reader margin
    :initarg :margin
    :type cl:integer
    :initform 0))
)

(cl:defclass LidarGoal (<LidarGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LidarGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LidarGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name actionlib_tutorials-msg:<LidarGoal> is deprecated: use actionlib_tutorials-msg:LidarGoal instead.")))

(cl:ensure-generic-function 'margin-val :lambda-list '(m))
(cl:defmethod margin-val ((m <LidarGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader actionlib_tutorials-msg:margin-val is deprecated.  Use actionlib_tutorials-msg:margin instead.")
  (margin m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LidarGoal>) ostream)
  "Serializes a message object of type '<LidarGoal>"
  (cl:let* ((signed (cl:slot-value msg 'margin)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LidarGoal>) istream)
  "Deserializes a message object of type '<LidarGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'margin) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LidarGoal>)))
  "Returns string type for a message object of type '<LidarGoal>"
  "actionlib_tutorials/LidarGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LidarGoal)))
  "Returns string type for a message object of type 'LidarGoal"
  "actionlib_tutorials/LidarGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LidarGoal>)))
  "Returns md5sum for a message object of type '<LidarGoal>"
  "56ede3025f9af8ca5f4030e86d8db223")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LidarGoal)))
  "Returns md5sum for a message object of type 'LidarGoal"
  "56ede3025f9af8ca5f4030e86d8db223")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LidarGoal>)))
  "Returns full string definition for message of type '<LidarGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32 margin~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LidarGoal)))
  "Returns full string definition for message of type 'LidarGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32 margin~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LidarGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LidarGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'LidarGoal
    (cl:cons ':margin (margin msg))
))
