; Auto-generated. Do not edit!


(cl:in-package actionlib_tutorials-msg)


;//! \htmlinclude LidarResult.msg.html

(cl:defclass <LidarResult> (roslisp-msg-protocol:ros-message)
  ((final
    :reader final
    :initarg :final
    :type cl:integer
    :initform 0))
)

(cl:defclass LidarResult (<LidarResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LidarResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LidarResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name actionlib_tutorials-msg:<LidarResult> is deprecated: use actionlib_tutorials-msg:LidarResult instead.")))

(cl:ensure-generic-function 'final-val :lambda-list '(m))
(cl:defmethod final-val ((m <LidarResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader actionlib_tutorials-msg:final-val is deprecated.  Use actionlib_tutorials-msg:final instead.")
  (final m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LidarResult>) ostream)
  "Serializes a message object of type '<LidarResult>"
  (cl:let* ((signed (cl:slot-value msg 'final)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LidarResult>) istream)
  "Deserializes a message object of type '<LidarResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'final) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LidarResult>)))
  "Returns string type for a message object of type '<LidarResult>"
  "actionlib_tutorials/LidarResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LidarResult)))
  "Returns string type for a message object of type 'LidarResult"
  "actionlib_tutorials/LidarResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LidarResult>)))
  "Returns md5sum for a message object of type '<LidarResult>"
  "e2aa29bfa110a0d8eeafa337cf7fa549")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LidarResult)))
  "Returns md5sum for a message object of type 'LidarResult"
  "e2aa29bfa110a0d8eeafa337cf7fa549")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LidarResult>)))
  "Returns full string definition for message of type '<LidarResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 final~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LidarResult)))
  "Returns full string definition for message of type 'LidarResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 final~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LidarResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LidarResult>))
  "Converts a ROS message object to a list"
  (cl:list 'LidarResult
    (cl:cons ':final (final msg))
))
