; Auto-generated. Do not edit!


(cl:in-package actionlib_tutorials-msg)


;//! \htmlinclude MoveToGoal.msg.html

(cl:defclass <MoveToGoal> (roslisp-msg-protocol:ros-message)
  ((point
    :reader point
    :initarg :point
    :type geometry_msgs-msg:Point
    :initform (cl:make-instance 'geometry_msgs-msg:Point)))
)

(cl:defclass MoveToGoal (<MoveToGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveToGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveToGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name actionlib_tutorials-msg:<MoveToGoal> is deprecated: use actionlib_tutorials-msg:MoveToGoal instead.")))

(cl:ensure-generic-function 'point-val :lambda-list '(m))
(cl:defmethod point-val ((m <MoveToGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader actionlib_tutorials-msg:point-val is deprecated.  Use actionlib_tutorials-msg:point instead.")
  (point m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveToGoal>) ostream)
  "Serializes a message object of type '<MoveToGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'point) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveToGoal>) istream)
  "Deserializes a message object of type '<MoveToGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'point) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveToGoal>)))
  "Returns string type for a message object of type '<MoveToGoal>"
  "actionlib_tutorials/MoveToGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveToGoal)))
  "Returns string type for a message object of type 'MoveToGoal"
  "actionlib_tutorials/MoveToGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveToGoal>)))
  "Returns md5sum for a message object of type '<MoveToGoal>"
  "a7c84ff13976aa04656e56e300124444")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveToGoal)))
  "Returns md5sum for a message object of type 'MoveToGoal"
  "a7c84ff13976aa04656e56e300124444")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveToGoal>)))
  "Returns full string definition for message of type '<MoveToGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# This is an action definition file, which has three parts: the goal~%# the result, and the feedback.~%# Part 1: the goal.~%#~%# The angle in degree the robot to turn, sent by client main~%geometry_msgs/Point point~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveToGoal)))
  "Returns full string definition for message of type 'MoveToGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# This is an action definition file, which has three parts: the goal~%# the result, and the feedback.~%# Part 1: the goal.~%#~%# The angle in degree the robot to turn, sent by client main~%geometry_msgs/Point point~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveToGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'point))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveToGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveToGoal
    (cl:cons ':point (point msg))
))
