; Auto-generated. Do not edit!


(cl:in-package actionlib_tutorials-msg)


;//! \htmlinclude MoveToGoal.msg.html

(cl:defclass <MoveToGoal> (roslisp-msg-protocol:ros-message)
  ((point
    :reader point
    :initarg :point
    :type geometry_msgs-msg:Point
    :initform (cl:make-instance 'geometry_msgs-msg:Point))
   (order
    :reader order
    :initarg :order
    :type cl:integer
    :initform 0))
)

(cl:defclass MoveToGoal (<MoveToGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveToGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveToGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name actionlib_tutorials-msg:<MoveToGoal> is deprecated: use actionlib_tutorials-msg:MoveToGoal instead.")))

(cl:ensure-generic-function 'point-val :lambda-list '(m))
(cl:defmethod point-val ((m <MoveToGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader actionlib_tutorials-msg:point-val is deprecated.  Use actionlib_tutorials-msg:point instead.")
  (point m))

(cl:ensure-generic-function 'order-val :lambda-list '(m))
(cl:defmethod order-val ((m <MoveToGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader actionlib_tutorials-msg:order-val is deprecated.  Use actionlib_tutorials-msg:order instead.")
  (order m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveToGoal>) ostream)
  "Serializes a message object of type '<MoveToGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'point) ostream)
  (cl:let* ((signed (cl:slot-value msg 'order)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveToGoal>) istream)
  "Deserializes a message object of type '<MoveToGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'point) istream)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'order) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveToGoal>)))
  "Returns string type for a message object of type '<MoveToGoal>"
  "actionlib_tutorials/MoveToGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveToGoal)))
  "Returns string type for a message object of type 'MoveToGoal"
  "actionlib_tutorials/MoveToGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveToGoal>)))
  "Returns md5sum for a message object of type '<MoveToGoal>"
  "6ebf71f49e07c108ca02b1e46a31ccaa")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveToGoal)))
  "Returns md5sum for a message object of type 'MoveToGoal"
  "6ebf71f49e07c108ca02b1e46a31ccaa")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveToGoal>)))
  "Returns full string definition for message of type '<MoveToGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# This is an action definition file, which has three parts: the goal~%# the result, and the feedback.~%# Part 1: the goal.~%#~%#Where to go~%geometry_msgs/Point point~%#The drone's id~%int32 order~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveToGoal)))
  "Returns full string definition for message of type 'MoveToGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# This is an action definition file, which has three parts: the goal~%# the result, and the feedback.~%# Part 1: the goal.~%#~%#Where to go~%geometry_msgs/Point point~%#The drone's id~%int32 order~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveToGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'point))
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveToGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveToGoal
    (cl:cons ':point (point msg))
    (cl:cons ':order (order msg))
))
